/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/api/v1/videos/{videoId}/progress": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations["progress"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/videos/{videoId}/favorite": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations["favorite"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/profiles/{profileId}/predictions": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations["predict"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/profiles/{profileId}/invite": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations["invite"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/profiles/{profileId}/fitness-tests": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations["register"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/profiles/claim": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations["claim"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/missions/{missionId}/participants/{profileId}/confirm": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations["confirm"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/missions/{missionId}/activity/timer": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations["timer"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/missions/{missionId}/activity/steps": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations["steps"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/families": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations["create"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/families/{familyId}/profiles": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["profiles"];
    put?: never;
    post: operations["addMember"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/families/{familyId}/missions": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["list"];
    put?: never;
    post: operations["create_1"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/families/{familyId}/coach/runs": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations["start"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/families/{familyId}/cheers": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations["cheer"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/coach/runs/{runId}/reject": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations["reject"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/coach/runs/{runId}/approve": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations["approve"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/coach/chat": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations["chat"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/auth/refresh": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations["refresh"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/auth/google": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations["google"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/auth/dev-login": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations["devLogin"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/profiles/{profileId}/support-mode": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch: operations["supportMode"];
    trace?: never;
  };
  "/api/v1/profiles/{profileId}/consent": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch: operations["consent"];
    trace?: never;
  };
  "/api/v1/videos": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["list_1"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/profiles/{profileId}/fitness-tests/latest": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["latest"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/me": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["me"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/fitness/items": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["items"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/families/{familyId}/report/weekly": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["weekly"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/families/{familyId}/fitness-map": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["fitnessMap"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/coach/runs/{runId}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    CurrentUser: {
      /** Format: uuid */
      userId?: string;
    };
    VideoProgressRequest: {
      /** Format: uuid */
      profileId?: string;
      /** Format: double */
      progress?: number;
      /** Format: int32 */
      watchedSec?: number;
      /** Format: uuid */
      missionId?: string | null;
    };
    VideoProgressView: {
      /** Format: double */
      maxProgress?: number;
      completed?: boolean;
      /** Format: int32 */
      creditedMinutes?: number;
      /** @enum {string|null} */
      verifiedBy?: "VIDEO_PROGRESS" | "TIMER" | "SELF_REPORT" | null;
      /** Format: double */
      missionProgress?: number | null;
    };
    FavoriteRequest: {
      /** Format: uuid */
      profileId?: string;
      favorited?: boolean;
    };
    FavoriteView: {
      videoId?: string;
      /** Format: uuid */
      profileId?: string;
      favorited?: boolean;
      /** Format: date-time */
      favoritedAt?: string | null;
    };
    PredictRequest: {
      /** Format: uuid */
      fitnessTestId?: string | null;
      /** Format: int32 */
      horizonYears?: number | null;
      itemCode?: string | null;
    };
    Point: {
      /** @enum {string} */
      scenario?: "MAINTAIN" | "IMPROVE";
      itemCode?: string;
      /** Format: int32 */
      yearsFromNow?: number;
      p10?: number | null;
      p50?: number | null;
      p90?: number | null;
    };
    PredictionResponse: {
      /** Format: uuid */
      predictionId?: string;
      modelVersion?: string;
      basis?: string;
      points?: components["schemas"]["Point"][];
      notice?: string;
    };
    InviteResponse: {
      claimCode?: string;
      /** Format: date-time */
      expiresAt?: string;
      shareUrl?: string;
    };
    ItemInput: {
      itemCode: string | null;
      value: number | null;
    };
    RegisterFitnessTestRequest: {
      /** Format: date */
      testedOn: string | null;
      /** @enum {string|null} */
      source: "SELF_INPUT" | "CENTER_SHEET" | null;
      heightCm?: number | null;
      weightKg?: number | null;
      items: components["schemas"]["ItemInput"][] | null;
    };
    FactorPoint: {
      /** @enum {string} */
      factor?:
        "심폐지구력" | "근력" | "근지구력" | "유연성" | "민첩성" | "순발력" | "협응력" | "평형성";
      itemCode?: string;
      /** Format: int32 */
      percentile?: number;
    };
    FitnessTestResponse: {
      /** Format: uuid */
      fitnessTestId?: string;
      /** Format: date */
      testedOn?: string;
      items?: components["schemas"]["ItemResult"][];
      weakest?: components["schemas"]["FactorPoint"] | null;
      strongest?: components["schemas"]["FactorPoint"] | null;
      disclaimer?: string;
    };
    ItemResult: {
      itemCode?: string;
      itemLabel?: string;
      unit?: string;
      value?: number;
      /** Format: int32 */
      percentile?: number | null;
      /** @enum {string|null} */
      grade?: "1등급" | "2등급" | "3등급" | "참가" | null;
      /** @enum {string|null} */
      band?: "strength" | "steady" | "growth" | null;
      topPercentText?: string | null;
    };
    ClaimRequest: {
      claimCode: string;
    };
    ClaimResponse: {
      /** Format: uuid */
      profileId?: string;
      /** Format: uuid */
      familyId?: string;
      /** @enum {string} */
      role?: "PARENT" | "CHILD";
      /** @enum {string} */
      nextStep?: "CREATE_FAMILY" | "CLAIM" | "HOME" | "SUPPORT_MODE";
    };
    ConfirmParticipantView: {
      /** Format: uuid */
      missionId?: string;
      /** Format: uuid */
      profileId?: string;
      completed?: boolean;
      /** @enum {string|null} */
      verifiedBy?: "VIDEO_PROGRESS" | "TIMER" | "SELF_REPORT" | null;
      /** Format: uuid */
      confirmedBy?: string | null;
      /** Format: date-time */
      verifiedAt?: string | null;
    };
    RecordTimerRequest: {
      /** Format: uuid */
      profileId?: string;
      /** Format: date-time */
      startedAt?: string;
      /** Format: date-time */
      endedAt?: string;
      /** Format: int32 */
      activeMinutes?: number;
    };
    TimerRecordedView: {
      /** Format: date */
      activityDate?: string;
      /** @enum {string} */
      source?: "MANUAL" | "TIMER" | "VIDEO";
      serverVerified?: boolean;
      /** Format: int32 */
      totalActiveMinutes?: number;
      /** Format: double */
      missionProgress?: number;
      missionCompleted?: boolean;
    };
    RecordStepsRequest: {
      /** Format: uuid */
      profileId?: string;
      /** Format: date */
      activityDate?: string;
      /** Format: int32 */
      steps?: number;
    };
    StepsRecordedView: {
      /** @enum {string} */
      source?: "MANUAL" | "TIMER" | "VIDEO";
      serverVerified?: boolean;
      /** @enum {string} */
      verifiedBy?: "VIDEO_PROGRESS" | "TIMER" | "SELF_REPORT";
      /** Format: double */
      missionProgress?: number;
      missionCompleted?: boolean;
      needsGuardianCheck?: boolean;
    };
    CreateFamilyRequest: {
      familyName: string;
      owner?: components["schemas"]["OwnerRequest"];
    };
    OwnerRequest: {
      name: string;
      /** Format: date */
      birthDate?: string;
      /** @enum {string} */
      sex?: "M" | "F";
    };
    FamilyCreatedResponse: {
      /** Format: uuid */
      familyId?: string;
      familyName?: string;
      ownerProfile?: components["schemas"]["ProfileSummary"];
    };
    ProfileSummary: {
      /** Format: uuid */
      profileId?: string;
      /** Format: uuid */
      familyId?: string;
      name?: string;
      /** @enum {string} */
      role?: "PARENT" | "CHILD";
      /** @enum {string} */
      ageGroup?: "유아기" | "유소년" | "청소년" | "성인" | "어르신";
      hasAccount?: boolean;
      /** @enum {string} */
      inviteStatus?: "NONE" | "ISSUED" | "EXPIRED" | "CLAIMED";
      /** @enum {string|null} */
      supportMode?: "CHEER_ONLY" | "WEEKEND" | "FULL" | null;
      measurable?: boolean;
      consentRequired?: boolean;
      consentGiven?: boolean;
    };
    AddMemberRequest: {
      name: string;
      /** Format: date */
      birthDate?: string;
      /** @enum {string} */
      sex?: "M" | "F";
      /** @enum {string} */
      role?: "PARENT" | "CHILD";
      guardianConsent?: components["schemas"]["GuardianConsentRequest"] | null;
    };
    GuardianConsentRequest: {
      personalData: boolean | null;
      healthData: boolean | null;
    };
    CreateMissionRequest: {
      title: string;
      /** Format: date */
      startDate?: string;
      /** Format: date */
      endDate?: string;
      /** @enum {string} */
      targetMetric?: "VIDEO_DONE" | "TIMER_MINUTES" | "STEPS";
      /** Format: int32 */
      targetValue?: number;
      videoId?: string | null;
      participantProfileIds: string[];
    };
    MissionCreatedView: {
      /** Format: uuid */
      missionId?: string;
      /** @enum {string} */
      origin?: "COACH" | "MANUAL";
      /** Format: uuid */
      coachRunId?: string | null;
      serverVerifiable?: boolean;
    };
    StartCoachRunRequest: {
      /** Format: date */
      weekStart?: string | null;
      /** Format: int32 */
      daysPerWeek?: number;
      /** Format: int32 */
      minutesPerSession?: number;
    };
    CoachRunAcceptedView: {
      /** Format: uuid */
      coachRunId?: string;
      /** @enum {string} */
      status?: "RUNNING" | "AWAITING_APPROVAL" | "APPROVED" | "REJECTED" | "FAILED";
      /** Format: int32 */
      pollAfterMs?: number;
    };
    CheerRequest: {
      /** Format: uuid */
      fromProfileId?: string;
      /** Format: uuid */
      toProfileId?: string;
      message?: string | null;
      emoji?: string | null;
      /** Format: uuid */
      missionId?: string | null;
      contentPresent?: boolean;
    };
    CheerResponse: {
      /** Format: uuid */
      cheerId?: string;
      /** Format: uuid */
      fromProfileId?: string;
      /** Format: uuid */
      toProfileId?: string;
      message?: string | null;
      emoji?: string | null;
      /** Format: uuid */
      missionId?: string | null;
      /** Format: date-time */
      createdAt?: string;
    };
    RejectCoachRunRequest: {
      reason?: string | null;
    };
    RejectCoachRunView: {
      /** Format: uuid */
      coachRunId?: string;
      /** @enum {string} */
      status?: "RUNNING" | "AWAITING_APPROVAL" | "APPROVED" | "REJECTED" | "FAILED";
      rejectedReason?: string | null;
      /** Format: int32 */
      missionCount?: number;
    };
    ApproveCoachRunView: {
      /** Format: uuid */
      coachRunId?: string;
      /** @enum {string} */
      status?: "RUNNING" | "AWAITING_APPROVAL" | "APPROVED" | "REJECTED" | "FAILED";
      /** Format: uuid */
      approvedBy?: string;
      /** Format: date-time */
      approvedAt?: string;
      createdMissions?: components["schemas"]["CreatedMissionView"][];
    };
    CreatedMissionView: {
      /** Format: uuid */
      missionId?: string;
      title?: string;
      /** @enum {string} */
      origin?: "COACH" | "MANUAL";
    };
    ChatRequest: {
      /** Format: uuid */
      profileId?: string;
      /** Format: uuid */
      conversationId?: string | null;
      question: string;
    };
    ChatCitationView: {
      /** Format: int32 */
      index?: number;
      sourceLabel?: string;
      excerpt?: string;
      url?: string | null;
    };
    ChatView: {
      /** Format: uuid */
      conversationId?: string;
      /** Format: uuid */
      messageId?: string;
      answer?: string;
      citations?: components["schemas"]["ChatCitationView"][];
      refused?: boolean;
      refusalReason?: string | null;
    };
    RefreshRequest: {
      refreshToken: string;
    };
    AuthResponse: {
      accessToken?: string;
      refreshToken?: string;
      /** Format: uuid */
      userId?: string;
      /** @enum {string} */
      nextStep?: "CREATE_FAMILY" | "CLAIM" | "HOME" | "SUPPORT_MODE";
      profiles?: components["schemas"]["ProfileSummary"][];
    };
    GoogleLoginRequest: {
      authorizationCode: string;
      redirectUri: string;
      claimCode?: string | null;
    };
    DevLoginRequest: {
      providerUserId: string;
      email?: string | null;
      claimCode?: string | null;
    };
    SupportModeRequest: {
      /** @enum {string} */
      supportMode?: "CHEER_ONLY" | "WEEKEND" | "FULL";
    };
    ConsentRequest: {
      personalData: boolean | null;
      healthData: boolean | null;
    };
    ConsentResponse: {
      consentGiven?: boolean;
      /** Format: date-time */
      consentAt?: string | null;
      /** Format: uuid */
      consentBy?: string | null;
      measurable?: boolean;
    };
    VideoLabel: {
      /** Format: int32 */
      ageFrom?: number | null;
      /** Format: int32 */
      ageTo?: number | null;
      factors?: string[];
      intensity?: string | null;
      space?: string | null;
      noise?: string | null;
      model?: string | null;
    };
    VideoListView: {
      videos?: components["schemas"]["VideoView"][];
      nextCursor?: string | null;
    };
    VideoView: {
      videoId?: string;
      title?: string;
      url?: string;
      thumbnailUrl?: string;
      /** Format: int32 */
      durationSec?: number | null;
      label?: components["schemas"]["VideoLabel"];
      badges?: string[];
      favorited?: boolean;
      /** Format: double */
      maxProgress?: number | null;
    };
    LatestFitnessResponse: {
      /** Format: uuid */
      fitnessTestId?: string | null;
      /** Format: date */
      testedOn?: string | null;
      radar?: components["schemas"]["RadarPointResponse"][];
      items?: components["schemas"]["ItemResult"][];
      weakest?: components["schemas"]["FactorPoint"] | null;
      strongest?: components["schemas"]["FactorPoint"] | null;
      /** @enum {string} */
      coachDirection?: "STRENGTHEN" | "GROWTH";
      disclaimer?: string;
    };
    RadarPointResponse: {
      /** @enum {string} */
      factor?:
        "심폐지구력" | "근력" | "근지구력" | "유연성" | "민첩성" | "순발력" | "협응력" | "평형성";
      /** Format: int32 */
      percentile?: number | null;
    };
    MeResponse: {
      /** Format: uuid */
      userId?: string;
      /** @enum {string} */
      nextStep?: "CREATE_FAMILY" | "CLAIM" | "HOME" | "SUPPORT_MODE";
      profiles?: components["schemas"]["ProfileSummary"][];
    };
    FitnessItemsResponse: {
      /** @enum {string} */
      ageGroup?: "유아기" | "유소년" | "청소년" | "성인" | "어르신";
      items?: components["schemas"]["Item"][];
    };
    Item: {
      itemCode?: string;
      itemName?: string;
      itemLabel?: string;
      unit?: string;
      /** @enum {string} */
      factor?:
        "심폐지구력" | "근력" | "근지구력" | "유연성" | "민첩성" | "순발력" | "협응력" | "평형성";
      higherIsBetter?: boolean;
      /** @enum {string} */
      inputGroup?: "EASY" | "EQUIPMENT";
      optional?: boolean;
      equipment?: string | null;
      range?: components["schemas"]["ValueRange"];
    };
    ValueRange: {
      /** Format: int32 */
      min?: number;
      /** Format: int32 */
      max?: number;
    };
    MemberReportView: {
      /** Format: uuid */
      profileId?: string;
      name?: string;
      /** Format: int32 */
      activeMinutes?: number;
      /** Format: int32 */
      verifiedMinutes?: number;
      /** Format: int32 */
      completedMissions?: number;
    };
    MissionStatsView: {
      /** Format: int32 */
      total?: number;
      /** Format: int32 */
      completed?: number;
    };
    WeeklyReportView: {
      /** Format: date */
      weekStart?: string;
      /** Format: date */
      weekEnd?: string;
      summary?: string | null;
      missionStats?: components["schemas"]["MissionStatsView"];
      members?: components["schemas"]["MemberReportView"][];
      /** Format: int32 */
      cheerCount?: number;
    };
    FamilyProfilesResponse: {
      /** Format: uuid */
      familyId?: string;
      familyName?: string;
      profiles?: components["schemas"]["ProfileSummary"][];
    };
    MissionListView: {
      missions?: components["schemas"]["MissionView"][];
    };
    MissionParticipantView: {
      /** Format: uuid */
      profileId?: string;
      name?: string | null;
      /** Format: double */
      progress?: number;
      completed?: boolean;
      /** @enum {string|null} */
      verifiedBy?: "VIDEO_PROGRESS" | "TIMER" | "SELF_REPORT" | null;
      needsGuardianCheck?: boolean;
    };
    MissionVideoView: {
      videoId?: string;
      title?: string | null;
      url?: string;
      /** Format: int32 */
      durationSec?: number | null;
      /** Format: int32 */
      startSec?: number | null;
    };
    MissionView: {
      /** Format: uuid */
      missionId?: string;
      title?: string;
      /** @enum {string} */
      origin?: "COACH" | "MANUAL";
      /** Format: uuid */
      coachRunId?: string | null;
      /** @enum {string} */
      targetMetric?: "VIDEO_DONE" | "TIMER_MINUTES" | "STEPS";
      /** Format: int32 */
      targetValue?: number;
      serverVerifiable?: boolean;
      /** Format: date */
      startDate?: string;
      /** Format: date */
      endDate?: string;
      rationale?: string | null;
      video?: components["schemas"]["MissionVideoView"] | null;
      participants?: components["schemas"]["MissionParticipantView"][];
    };
    FitnessMapResponse: {
      /** Format: uuid */
      familyId?: string;
      familyName?: string | null;
      members?: components["schemas"]["Member"][];
      disclaimer?: string;
    };
    Latest: {
      /** Format: uuid */
      fitnessTestId?: string;
      /** Format: date */
      testedOn?: string;
      /** Format: int32 */
      overallPercentile?: number | null;
      weakest?: components["schemas"]["FactorPoint"] | null;
      strongest?: components["schemas"]["FactorPoint"] | null;
      /** @enum {string} */
      coachDirection?: "STRENGTHEN" | "GROWTH";
    };
    Member: {
      /** Format: uuid */
      profileId?: string;
      name?: string;
      /** @enum {string} */
      role?: "PARENT" | "CHILD";
      /** @enum {string} */
      ageGroup?: "유아기" | "유소년" | "청소년" | "성인" | "어르신";
      hasAccount?: boolean;
      /** @enum {string|null} */
      supportMode?: "CHEER_ONLY" | "WEEKEND" | "FULL" | null;
      measurable?: boolean;
      consentRequired?: boolean;
      consentGiven?: boolean;
      headline?: string | null;
      latest?: components["schemas"]["Latest"] | null;
    };
    CoachRunView: {
      /** Format: uuid */
      coachRunId?: string;
      /** Format: uuid */
      familyId?: string;
      /** @enum {string} */
      status?: "RUNNING" | "AWAITING_APPROVAL" | "APPROVED" | "REJECTED" | "FAILED";
      /** Format: date */
      weekStart?: string;
      summary?: string | null;
      steps?: components["schemas"]["CoachStep"][];
      proposals?: components["schemas"]["ProposalView"][] | null;
      canApprove?: boolean;
      /** Format: int32 */
      missionCount?: number;
      rejectedReason?: string | null;
    };
    CoachStep: {
      /** Format: int32 */
      seq?: number;
      name?: string;
      status?: string;
      summary?: string;
    };
    ProposalCitationView: {
      /** Format: int32 */
      index?: number;
      label?: string;
      chunkId?: string;
      url?: string | null;
    };
    ProposalParticipantView: {
      /** Format: uuid */
      profileId?: string;
      /** @enum {string} */
      role?: "PARENT" | "CHILD";
      coachRole?: string;
    };
    ProposalVideoView: {
      videoId?: string;
      title?: string | null;
      url?: string;
      /** Format: int32 */
      startSec?: number | null;
      badges?: string[];
    };
    ProposalView: {
      /** Format: int32 */
      position?: number;
      title?: string;
      rationale?: string | null;
      targetMetric?: string;
      /** Format: int32 */
      targetValue?: number;
      /** Format: date */
      startDate?: string;
      /** Format: date */
      endDate?: string;
      participants?: components["schemas"]["ProposalParticipantView"][];
      video?: components["schemas"]["ProposalVideoView"] | null;
      citations?: components["schemas"]["ProposalCitationView"][];
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  progress: {
    parameters: {
      query: {
        user: components["schemas"]["CurrentUser"];
      };
      header?: never;
      path: {
        videoId: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["VideoProgressRequest"];
      };
    };
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["VideoProgressView"];
        };
      };
    };
  };
  favorite: {
    parameters: {
      query: {
        user: components["schemas"]["CurrentUser"];
      };
      header?: never;
      path: {
        videoId: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["FavoriteRequest"];
      };
    };
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["FavoriteView"];
        };
      };
    };
  };
  predict: {
    parameters: {
      query: {
        user: components["schemas"]["CurrentUser"];
      };
      header?: never;
      path: {
        profileId: string;
      };
      cookie?: never;
    };
    requestBody?: {
      content: {
        "application/json": components["schemas"]["PredictRequest"];
      };
    };
    responses: {
      /** @description Created */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["PredictionResponse"];
        };
      };
    };
  };
  invite: {
    parameters: {
      query: {
        user: components["schemas"]["CurrentUser"];
      };
      header?: never;
      path: {
        profileId: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Created */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["InviteResponse"];
        };
      };
    };
  };
  register: {
    parameters: {
      query: {
        user: components["schemas"]["CurrentUser"];
      };
      header?: never;
      path: {
        profileId: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["RegisterFitnessTestRequest"];
      };
    };
    responses: {
      /** @description Created */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["FitnessTestResponse"];
        };
      };
    };
  };
  claim: {
    parameters: {
      query: {
        user: components["schemas"]["CurrentUser"];
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["ClaimRequest"];
      };
    };
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ClaimResponse"];
        };
      };
    };
  };
  confirm: {
    parameters: {
      query: {
        user: components["schemas"]["CurrentUser"];
      };
      header?: never;
      path: {
        missionId: string;
        profileId: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ConfirmParticipantView"];
        };
      };
    };
  };
  timer: {
    parameters: {
      query: {
        user: components["schemas"]["CurrentUser"];
      };
      header?: never;
      path: {
        missionId: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["RecordTimerRequest"];
      };
    };
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["TimerRecordedView"];
        };
      };
    };
  };
  steps: {
    parameters: {
      query: {
        user: components["schemas"]["CurrentUser"];
      };
      header?: never;
      path: {
        missionId: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["RecordStepsRequest"];
      };
    };
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["StepsRecordedView"];
        };
      };
    };
  };
  create: {
    parameters: {
      query: {
        user: components["schemas"]["CurrentUser"];
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["CreateFamilyRequest"];
      };
    };
    responses: {
      /** @description Created */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["FamilyCreatedResponse"];
        };
      };
    };
  };
  profiles: {
    parameters: {
      query: {
        user: components["schemas"]["CurrentUser"];
      };
      header?: never;
      path: {
        familyId: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["FamilyProfilesResponse"];
        };
      };
    };
  };
  addMember: {
    parameters: {
      query: {
        user: components["schemas"]["CurrentUser"];
      };
      header?: never;
      path: {
        familyId: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["AddMemberRequest"];
      };
    };
    responses: {
      /** @description Created */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ProfileSummary"];
        };
      };
    };
  };
  list: {
    parameters: {
      query: {
        user: components["schemas"]["CurrentUser"];
        scope?: "ALL" | "MINE" | "FAMILY";
        status?: "ACTIVE" | "DONE" | "EXPIRED";
      };
      header?: never;
      path: {
        familyId: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["MissionListView"];
        };
      };
    };
  };
  create_1: {
    parameters: {
      query: {
        user: components["schemas"]["CurrentUser"];
      };
      header?: never;
      path: {
        familyId: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["CreateMissionRequest"];
      };
    };
    responses: {
      /** @description Created */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["MissionCreatedView"];
        };
      };
    };
  };
  start: {
    parameters: {
      query: {
        user: components["schemas"]["CurrentUser"];
      };
      header?: never;
      path: {
        familyId: string;
      };
      cookie?: never;
    };
    requestBody?: {
      content: {
        "application/json": components["schemas"]["StartCoachRunRequest"];
      };
    };
    responses: {
      /** @description Accepted */
      202: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["CoachRunAcceptedView"];
        };
      };
    };
  };
  cheer: {
    parameters: {
      query: {
        user: components["schemas"]["CurrentUser"];
      };
      header?: never;
      path: {
        familyId: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["CheerRequest"];
      };
    };
    responses: {
      /** @description Created */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["CheerResponse"];
        };
      };
    };
  };
  reject: {
    parameters: {
      query: {
        user: components["schemas"]["CurrentUser"];
      };
      header?: never;
      path: {
        runId: string;
      };
      cookie?: never;
    };
    requestBody?: {
      content: {
        "application/json": components["schemas"]["RejectCoachRunRequest"];
      };
    };
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["RejectCoachRunView"];
        };
      };
    };
  };
  approve: {
    parameters: {
      query: {
        user: components["schemas"]["CurrentUser"];
      };
      header?: never;
      path: {
        runId: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApproveCoachRunView"];
        };
      };
    };
  };
  chat: {
    parameters: {
      query: {
        user: components["schemas"]["CurrentUser"];
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["ChatRequest"];
      };
    };
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ChatView"];
        };
      };
    };
  };
  refresh: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["RefreshRequest"];
      };
    };
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["AuthResponse"];
        };
      };
    };
  };
  google: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["GoogleLoginRequest"];
      };
    };
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["AuthResponse"];
        };
      };
    };
  };
  devLogin: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["DevLoginRequest"];
      };
    };
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["AuthResponse"];
        };
      };
    };
  };
  supportMode: {
    parameters: {
      query: {
        user: components["schemas"]["CurrentUser"];
      };
      header?: never;
      path: {
        profileId: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["SupportModeRequest"];
      };
    };
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ProfileSummary"];
        };
      };
    };
  };
  consent: {
    parameters: {
      query: {
        user: components["schemas"]["CurrentUser"];
      };
      header?: never;
      path: {
        profileId: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["ConsentRequest"];
      };
    };
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ConsentResponse"];
        };
      };
    };
  };
  list_1: {
    parameters: {
      query: {
        user: components["schemas"]["CurrentUser"];
        list?: "ALL" | "FAVORITES" | "RECENT";
        profileId?: string;
        ageGroup?: string;
        factor?: string;
        cursor?: string;
        size?: number;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["VideoListView"];
        };
      };
    };
  };
  latest: {
    parameters: {
      query: {
        user: components["schemas"]["CurrentUser"];
      };
      header?: never;
      path: {
        profileId: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["LatestFitnessResponse"];
        };
      };
    };
  };
  me: {
    parameters: {
      query: {
        user: components["schemas"]["CurrentUser"];
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["MeResponse"];
        };
      };
    };
  };
  items: {
    parameters: {
      query: {
        ageGroup: string;
        sex?: string;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["FitnessItemsResponse"];
        };
      };
    };
  };
  weekly: {
    parameters: {
      query: {
        user: components["schemas"]["CurrentUser"];
        weekStart?: string;
      };
      header?: never;
      path: {
        familyId: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["WeeklyReportView"];
        };
      };
    };
  };
  fitnessMap: {
    parameters: {
      query: {
        user: components["schemas"]["CurrentUser"];
      };
      header?: never;
      path: {
        familyId: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["FitnessMapResponse"];
        };
      };
    };
  };
  get: {
    parameters: {
      query: {
        user: components["schemas"]["CurrentUser"];
      };
      header?: never;
      path: {
        runId: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["CoachRunView"];
        };
      };
    };
  };
}
